[package]
name = "lngap-harness"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lngap-btc = { path = "../btc" }
lngap-lamport = { path = "../lamport" }
lngap-channel = { path = "../channel" }
lngap-contract = { path = "../contract" }
lngap-party = { path = "../party" }
bitcoin.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
lngap-tictactoe = { path = "../apps/tictactoe" }
lngap-names = { path = "../apps/names" }
lngap-spv = { path = "../apps/spv" }
lngap-n4bit = { path = "../n4bit" }
lngap-factchain = { path = "../apps/factchain" }
lngap-names-fc = { path = "../apps/names-fc" }
serde_json.workspace = true
hex.workspace = true
bitcoincore-rpc.workspace = true
