//! A contract between Alice and the hub (LN-GAP v3, research/lngap_v3.pdf)
//! as both parties build it: its terms and keys ([`Spec`]), its trees, and
//! every transaction the two pre-sign when it is opened ([`Presign`]).
//!
//! The contract output carries `fold` (the cooperative close, signed when
//! it happens), `default` and `escalate`; a dispute is
//! BitVMX's search over the statement program, played on the ladder from
//! move 1 with lean moves (lngap-v25, lngap-zk). What is pre-signed:
//! - the chain's links: `escalate` (move 1) and each move's `post`, TRUC
//!   (v3) transactions at zero fee with a zero-value anchor, each signed
//!   against the previous link's txid (fixed, since nothing can be added
//!   to a link: its poster pays with a child spending the anchor);
//! - the transactions that end the chain: the default, each ladder
//!   output's timeout (`split`), the final step's proofs; signed
//!   ALL|ANYONECANPAY at zero fee, so their broadcaster adds a fee input.

use std::collections::HashMap;
use std::sync::{Arc, Mutex};

use anyhow::{bail, ensure, Context, Result};
use bitcoin::key::{Keypair, XOnlyPublicKey};
use bitcoin::secp256k1::{schnorr, SECP256K1};
use bitcoin::taproot::ControlBlock;
use bitcoin::transaction::Version;
use bitcoin::{Amount, OutPoint, ScriptBuf, Transaction, TxOut};
use lngap_btc::keys::Seed;
use lngap_btc::sighash::{sign_tapscript, sign_tapscript_acp, tapscript_sighash};
use lngap_btc::taptree::TapTree;
use lngap_btc::tx::build_spend;
use lngap_btc::witness::tapscript_witness;
use lngap_channel::{ChannelParams, CommitCtx, PartyPubKeys, Role};
use lngap_contract::{Outcome, Payout};
use lngap_lamport::keystore::KeyStore;
use lngap_lamport::winternitz::WotsPublic;
use lngap_pos::instance::{mover_at, PosDepthKeys};
use lngap_pos::ttt::Layout;
use lngap_v25::{escalate_leaf_with, ladder_leaves, ZkDated};
use lngap_zk::challenges::ProgramInfo;
use lngap_zk::family::ZkFamily;
use lngap_zk::game::Search;

use crate::session::{default_leaf, default_outputs, fold_leaf, input_word_leaf, payout, Terms};

/// The search game's id inside the leaves' layout.
pub const GAME_ID: u16 = 1;
/// The commitment sequence the leaves are built under (a standalone
/// contract has one).
pub const SEQ: u64 = 1;

/// The statement program the dispute runs: BitVMX's program definition
/// and what the leaves need from it.
pub struct Program {
    pub pdf: String,
    pub info: ProgramInfo,
    pub rounds: u32,
}

impl Program {
    pub fn load(pdf: &str) -> Result<Program> {
        let info = ProgramInfo::load(pdf)?;
        let def = emulator::loader::program_definition::ProgramDefinition::from_config(pdf).map_err(|e| anyhow::anyhow!("{pdf}: {e:?}"))?;
        Ok(Program { pdf: pdf.to_string(), info, rounds: u32::from(def.nary_def().total_rounds()) })
    }
    pub fn search(&self) -> Search {
        Search { game_id: GAME_ID, rounds: self.rounds }
    }
    /// The search's depths (moves).
    pub fn depths(&self) -> u32 {
        self.search().depths()
    }
}

/// An input-word check on the first ladder output: word `word` must be
/// `value`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Check {
    pub name: String,
    pub word: usize,
    pub value: u32,
}

/// What both parties agree when they open a contract.
#[derive(Clone)]
pub struct Spec {
    pub terms: Terms,
    /// The contract's number; the memo `c` is `terms.id`.
    pub cid: u32,
    pub params: ChannelParams,
    /// Alice's keys, then the hub's.
    pub pubs: [PartyPubKeys; 2],
    /// The input word carrying `b`, and the input-word checks.
    pub b_word: usize,
    pub checks: Vec<Check>,
    /// The move keys by depth (`moves[d - 1]`, generated by depth `d`'s
    /// mover), each signing its move's 48-byte head.
    pub moves: Vec<WotsPublic>,
    /// Alice's input-word keys, one per word of the statement's input.
    pub inputs: Vec<WotsPublic>,
}

/// The two outcomes a dispute ends in.
pub fn outcomes() -> Vec<Outcome> {
    vec![Outcome::new(0, "UserWins", Payout::UserAll), Outcome::new(1, "HubWins", Payout::HubAll)]
}

/// Lamport keys the venue-era fields of a depth's key set want (the move
/// code, the claimant code); a v3 contract's leaves never use them.
fn unused_code_keys(m: u32) -> Result<Vec<lngap_lamport::PublicKey>> {
    let mut ks = KeyStore::new(Seed::from_label("lngap-v3/unused-code-keys"));
    (1..=m).map(|d| ks.generate(&format!("code/{d}"), lngap_contract::CODE_BITS)).collect()
}

/// A contract, its trees built once.
pub struct Contract {
    pub spec: Spec,
    keys: Vec<PosDepthKeys>,
    family: Arc<ZkFamily>,
    outcomes: Vec<Outcome>,
    ladders: Mutex<HashMap<u32, TapTree>>,
}

impl Contract {
    pub fn new(spec: Spec, program: &Program) -> Result<Contract> {
        let m = program.depths();
        ensure!(spec.moves.len() as u32 == m, "{} move keys for {m} depths", spec.moves.len());
        ensure!(spec.inputs.len() == program.info.input_words, "{} input keys for {} words", spec.inputs.len(), program.info.input_words);
        ensure!(spec.b_word < spec.inputs.len() && spec.checks.iter().all(|c| c.word < spec.inputs.len()), "an input word out of range");
        let codes = unused_code_keys(m)?;
        let keys = spec
            .moves
            .iter()
            .zip(codes)
            .enumerate()
            .map(|(i, (k, code))| PosDepthKeys { mover: mover_at(i as u32 + 1), rebut: k.clone(), mover_code: code.clone(), claimant_code: code, state: k.clone() })
            .collect();
        let family = ZkFamily::lean(program.search(), program.info.clone(), spec.inputs.clone(), spec.moves.clone());
        Ok(Contract { spec, keys, family, outcomes: outcomes(), ladders: Mutex::new(HashMap::new()) })
    }
    /// The search's depths.
    pub fn m(&self) -> u32 {
        self.keys.len() as u32
    }
    pub fn ctx(&self) -> CommitCtx<'_> {
        CommitCtx { params: &self.spec.params, keys: &self.spec.pubs, broadcaster: Role::Hub, seq: SEQ, rev_hash: [0u8; 20] }
    }
    pub fn dated(&self) -> ZkDated<'_> {
        ZkDated { family: self.family.as_ref(), prove_presigned: true }
    }
    pub fn b_key(&self) -> &WotsPublic {
        &self.spec.inputs[self.spec.b_word]
    }
    /// The input words `escalate` puts on chain: `b`'s and the checked ones.
    pub fn claim_words(&self) -> Vec<usize> {
        let mut w: Vec<usize> = self.spec.checks.iter().map(|c| c.word).chain([self.spec.b_word]).collect();
        w.sort_unstable();
        w.dedup();
        w
    }
    /// What the contract output holds: `V_max` and both reserves (it funds
    /// no fees).
    pub fn value(&self) -> Amount {
        self.spec.terms.v_max() + self.spec.terms.reserves()
    }
    /// The contract output's tree: `fold`, `default` and `escalate`.
    pub fn tree(&self) -> Result<TapTree> {
        let ctx = self.ctx();
        let l1 = Layout::at(1, GAME_ID, mover_at(1));
        let words: Vec<WotsPublic> = self.claim_words().iter().map(|&j| self.spec.inputs[j].clone()).collect();
        TapTree::new(vec![fold_leaf(&ctx), default_leaf(&ctx, self.spec.terms.t_close), escalate_leaf_with(&self.dated(), &ctx, &l1, &self.keys[0], &words)])
    }
    /// The cooperative close for a withdrawal of `b` sats, the contract
    /// output at `funding`: Alice `b + r_A`, the hub the rest less `fee`.
    /// Both sign it when it happens ([`Presign::sign`], ALL).
    pub fn fold(&self, funding: OutPoint, b: Amount, fee: Amount) -> Result<Presign> {
        let t = &self.spec.terms;
        ensure!(b <= t.v_max(), "{b} is above the cap {}", t.v_max());
        let tree = self.tree()?;
        let c_out = TxOut { value: self.value(), script_pubkey: tree.script_pubkey() };
        let alice = b + t.reserve_alice;
        let hub = (c_out.value - alice).checked_sub(fee).context("the fee")?;
        let mut outs = vec![TxOut { value: alice, script_pubkey: self.spec.pubs[0].payout_spk.clone() }];
        if hub >= self.spec.params.dust {
            outs.push(TxOut { value: hub, script_pubkey: self.spec.pubs[1].payout_spk.clone() });
        }
        // signed like a link (plain ALL: its fee comes from the hub's
        // output, nothing is added to it), but an ordinary transaction
        let mut p = Presign::new("fold", &tree, "fold", funding, &c_out, outs, true)?;
        p.tx.version = Version::TWO;
        Ok(p)
    }
    /// The ladder output after move `j`; the first also carries the hub's
    /// input-word checks.
    pub fn ladder(&self, j: u32) -> Result<TapTree> {
        if let Some(t) = self.ladders.lock().unwrap().get(&j) {
            return Ok(t.clone());
        }
        let ctx = self.ctx();
        let mut leaves = ladder_leaves(&self.dated(), &ctx, GAME_ID, j, &self.keys, &self.outcomes);
        if j == 1 {
            leaves.extend(self.spec.checks.iter().map(|c| input_word_leaf(&ctx, &c.name, &self.spec.inputs[c.word], c.value)));
        }
        let t = TapTree::new(leaves)?;
        self.ladders.lock().unwrap().insert(j, t.clone());
        Ok(t)
    }
    /// Who is paid if the ladder output after move `j` times out: the mover
    /// of `j`, except at the last depth, where Alice must prove the step.
    pub fn timeout_payee(&self, j: u32) -> Role {
        if j == self.m() {
            mover_at(j).other()
        } else {
            mover_at(j)
        }
    }
    /// The outputs paying `b` in bits and both reserves to Alice, the rest
    /// to the hub.
    pub fn pay_alice(&self, available: Amount) -> Result<Vec<TxOut>> {
        payout(&self.ctx(), &self.spec.terms, self.b_key(), available, Amount::ZERO)
    }
    /// Everything to the hub.
    pub fn pay_hub(&self, available: Amount) -> Vec<TxOut> {
        vec![TxOut { value: available, script_pubkey: self.spec.pubs[1].payout_spk.clone() }]
    }

    /// Every transaction the two parties pre-sign, the contract output at
    /// `funding`: the default; the chain (escalate, then a post per move);
    /// each ladder output's timeout; the final step's proofs.
    pub fn presign(&self, funding: OutPoint) -> Result<Vec<Presign>> {
        let tree = self.tree()?;
        let c_out = TxOut { value: self.value(), script_pubkey: tree.script_pubkey() };
        let mut out = vec![];
        let outs = default_outputs(&self.ctx(), &self.spec.terms, c_out.value, Amount::ZERO)?;
        out.push(Presign::new("default", &tree, "default", funding, &c_out, outs, false)?);
        // the chain
        let (mut prev_tree, mut prev_leaf, mut op, mut prev_out) = (tree, "escalate".to_string(), funding, c_out);
        for j in 1..=self.m() {
            let t = self.ladder(j)?;
            let t_out = TxOut { value: prev_out.value, script_pubkey: t.script_pubkey() };
            let anchor = TxOut { value: Amount::ZERO, script_pubkey: ScriptBuf::new_p2a() };
            let link = Presign::new(&format!("move_{j}"), &prev_tree, &prev_leaf, op, &prev_out, vec![t_out.clone(), anchor], true)?;
            op = OutPoint { txid: link.tx.compute_txid(), vout: 0 };
            out.push(link);
            // this ladder output's timeout
            let payee = self.timeout_payee(j);
            let name = if payee == Role::User { "split_UserWins" } else { "split_HubWins" };
            let outs = if payee == Role::User { self.pay_alice(t_out.value)? } else { self.pay_hub(t_out.value) };
            out.push(Presign::new(&format!("timeout_{j}"), &t, name, op, &t_out, outs, false)?);
            (prev_tree, prev_leaf, prev_out) = (t, "post".to_string(), t_out);
        }
        // the final step's proofs, one per instruction class
        let last = self.ladder(self.m())?;
        for leaf in last.leaves().iter().filter(|l| l.name.starts_with("zk_prove_")) {
            let outs = self.pay_alice(prev_out.value)?;
            out.push(Presign::new(&format!("prove_{}", &leaf.name["zk_prove_".len()..]), &last, &leaf.name, op, &prev_out, outs, false)?);
        }
        Ok(out)
    }
}

/// One pre-signed transaction: unsigned, with what its signatures cover.
#[derive(Clone, Debug)]
pub struct Presign {
    pub name: String,
    pub tx: Transaction,
    pub prevout: TxOut,
    pub leaf: ScriptBuf,
    pub control: ControlBlock,
    /// A link of the chain (TRUC, plain ALL signatures, an anchor at output
    /// 1); otherwise a terminal transaction (ALL|ANYONECANPAY).
    pub link: bool,
}

impl Presign {
    fn new(name: &str, tree: &TapTree, leaf: &str, op: OutPoint, prevout: &TxOut, outputs: Vec<TxOut>, link: bool) -> Result<Presign> {
        let l = tree.leaf(leaf).with_context(|| format!("{name}: no leaf {leaf}"))?;
        let mut tx = build_spend(op, &l.timelock, outputs);
        if link {
            tx.version = Version(3);
        }
        Ok(Presign { name: name.to_string(), tx, prevout: prevout.clone(), leaf: l.script.clone(), control: tree.control_block(leaf)?, link })
    }
    /// This party's signature.
    pub fn sign(&self, kp: &Keypair) -> Result<Vec<u8>> {
        if self.link {
            Ok(sign_tapscript(kp, &self.tx, 0, std::slice::from_ref(&self.prevout), &self.leaf)?.as_ref().to_vec())
        } else {
            sign_tapscript_acp(kp, &self.tx, 0, &self.prevout, &self.leaf)
        }
    }
    /// Check the other party's signature.
    pub fn verify(&self, pk: &XOnlyPublicKey, sig: &[u8]) -> Result<()> {
        if self.link {
            let s = schnorr::Signature::from_slice(sig)?;
            let msg = tapscript_sighash(&self.tx, 0, std::slice::from_ref(&self.prevout), &self.leaf)?;
            SECP256K1.verify_schnorr(&s, &msg, pk).map_err(|e| anyhow::anyhow!("{}: {e}", self.name))
        } else {
            ensure!(sig.len() == 65 && sig[64] == bitcoin::sighash::TapSighashType::AllPlusAnyoneCanPay as u8, "{}: not an ALL|ANYONECANPAY signature", self.name);
            let s = schnorr::Signature::from_slice(&sig[..64])?;
            let leaf_hash = bitcoin::taproot::TapLeafHash::from_script(&self.leaf, bitcoin::taproot::LeafVersion::TapScript);
            let h = bitcoin::sighash::SighashCache::new(&self.tx).taproot_script_spend_signature_hash(0, &bitcoin::sighash::Prevouts::One(0, &self.prevout), leaf_hash, bitcoin::sighash::TapSighashType::AllPlusAnyoneCanPay)?;
            let msg = bitcoin::secp256k1::Message::from_digest(bitcoin::hashes::Hash::to_byte_array(h));
            SECP256K1.verify_schnorr(&s, &msg, pk).map_err(|e| anyhow::anyhow!("{}: {e}", self.name))
        }
    }
    /// The transaction ready to broadcast: `wire` (the leaf's own witness,
    /// such as a move) below the hub's and Alice's signatures.
    pub fn finish(&self, wire: Vec<Vec<u8>>, hub_sig: &[u8], alice_sig: &[u8]) -> Transaction {
        let mut tx = self.tx.clone();
        let mut w = wire;
        w.push(hub_sig.to_vec());
        w.push(alice_sig.to_vec());
        tx.input[0].witness = tapscript_witness(&w, &self.leaf, &self.control);
        tx
    }
}

/// Both parties' signatures on a contract's pre-signed set, by name.
#[derive(Clone, Debug, Default)]
pub struct Signed {
    pub hub: HashMap<String, Vec<u8>>,
    pub alice: HashMap<String, Vec<u8>>,
}

impl Signed {
    /// Check every signature of both parties on `set`.
    pub fn verify(&self, set: &[Presign], pubs: &[PartyPubKeys; 2]) -> Result<()> {
        for p in set {
            let (Some(h), Some(a)) = (self.hub.get(&p.name), self.alice.get(&p.name)) else {
                bail!("{}: a signature is missing", p.name);
            };
            p.verify(&pubs[1].payment, h)?;
            p.verify(&pubs[0].payment, a)?;
        }
        Ok(())
    }
}

/// One party's signatures on the whole set.
pub fn sign_all(set: &[Presign], kp: &Keypair) -> Result<HashMap<String, Vec<u8>>> {
    set.iter().map(|p| Ok((p.name.clone(), p.sign(kp)?))).collect()
}
